key: 9pjhrCTE8aoY38z/GjmIC0XTQhomRHIt+AoR5urLRiOYo9jH8PZKnCxqNBgrtIxpa+YkprAOosTQ64j4DAZ4c6Z7sVgfbef+lmxzPT7XaHc3YwbgAy+6bu+vyC3nQ24Q5S1M4TdLz0gvL28sf8y0dk4JYt1TU996fRSzjL1mr7eV7npnPobTsvV8I3m14CQbkPypxxurJc6wGwYeS/bvCvpogotr9mmG9qNfeD7vNJ5XMUgIZcWmddDN+0/jpwrzclmWs4VGx9PMsrrXhnnAvYVxcWd8Zre/8BxSR+lxWmBdAs77/u7Eb50F/UBPBc97W48637EUDmJ3f10wknQHmMpRfBBXuKbYXqJ9wjNhmNmXb+JiF8JbsGIcBSNlDCZHcMYpd9cPGYieX73sVDpJMYr4FdiqFpsJyiG59f1N9BY5xAF0EQQBpnWJhN995JG/M5jFAUDrgiuavnQcURBxp2D+DBZUQO/sv61hoGX8aVGODnB4v8d5nbNTPT7a7PBYuZWxjo3xDLZKpcuf2ZL6OnJpinLYYSlQwTTc1pi4ww0hJtyUg7ujHHNWKUqlnDCHeej51RMsixEfM0lmuL0Iuzjbq4eMoirfj9rxEfPffjlECM9GafKgSWrULVJTRPl7zJxc4uX2TucOSJTeNS2wJLON+L30NfCDtTax0kxtm44=
metrics:
  plugins:
    - name: jvmjolokia
      interval: 300
      enabled: true
      config:
        ip: 127.0.0.1
        password: admin
        protocol: http
        username: admin
        port: 8778
        context: jolokia
        monitorDeadlocks: false
        deadLockMonitoringInterval: 300
